### PR TITLE
Updated mountain figure.

### PR DESCRIPTION
**Pull request by TanyaS08**
I've double checked the treatments/sites for the different datasets against the data files in the `clean_data`. Might be worth a second set of eyes. Also recoloured dry season to be darker since the light colours tended to disappear a bit too much let me know if the contrast is enough though 😊

### CODE REVIEW

**Review by audhalbritter — COMMENTED** [review]
The site/treatment/season combinations look good. The only one I am uncertain about is the height/structure dataset for ACJ NB. Why is this only available for the dry season and not wet. All the other NB datasets are for both wet and dry season. I have not checked this but it seems strange.

**Comment by audhalbritter** [comment]
I like the mountain figure very much now. But the B and NB wet and dry are a bit hard to distinguish. Maybe it is my screen, but making one of them a tick brighter might help.
And the other thing I was wondering about is if the table needs a site column. You have to look at the table and then the site column all the way to the right to see which site you are looking at. I think it would work with 3-4 sites, but because we have 6 it takes a bit more... do you think there is space for a site column in the table?

**Comment by TanyaS08** [comment]
> The site/treatment/season combinations look good. The only one I am uncertain about is the height/structure dataset for ACJ NB. Why is this only available for the dry season and not wet. All the other NB datasets are for both wet and dry season. I have not checked this but it seems strange.

I had a look and (in the dataset) we don't have that info at all. I think its because we would've collected wet season NB data in PFTC5 and those are the data sheets we are still trying to track down i.e. still missing... So as it stands we don't have that data but in theory we do...

**Comment by audhalbritter** [comment]
Oh ok that's the problem. I should ask Lucely and Paul if those datasheets can be found somewhere...

**Comment by TanyaS08** [comment]
Updated the mountain figure - went back to 'light mode' for the dry season squares but thinking a patterned fill might be a good idea?

**Comment by audhalbritter** [comment]
lighter is better I think, but maybe a pattern fill might be even better!

**Pull request merged**
